name: rope
description: "A fast, immutable rope data structure in Dart using a SumTree architecture. Inspired by Zed's implementation, this rope is optimized for large-scale string manipulation and editor-like use cases."
version: 0.0.2
homepage: https://github.com/iamngoni/rope

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^7.0.0
